[[redirects]]
from = "/index"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/Index2"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/Index3"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/pass-through"
to = "/index.html"
status = 200
