[[redirects]]
from = "/index"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/Index2"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/Index3"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/Index-4"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/Index_5"
to = "https://www.youtube.com/"
status = 200
