[[redirects]]
from = "/HTML/index"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/HTML/Index2"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/HTML/Index3"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/HTML/Index-4"
to = "https://www.youtube.com/"
status = 200

[[redirects]]
from = "/HTML/Index_5"
to = "https://www.youtube.com/"
status = 200
